### ISSUE TITLE
Maintain a KIE/BAMOE library with examples organized by technology and industry use-cases spreading the knowledge base

### ISSUE THREAD

**Issue by tiagobento** [IBM/bamoe-issues#196]
> Originally reported by @eduardocerqueira
>
> to be used as reference: https://github.com/kiegroup/kogito-examples
> 
> 1. define a plan and add a short proposal
> 2. engage with others participants for collaboration (Karina, dev.*)

**Comment by tiagobento** [comment]
Briefly discussed this with Alex and Tim, I think the gist of it would be us having a set of models / projects that can be used to assess our technology. Since there's a lot of ways to "organize" such things, we thought that a good starting point would be separating by

1. Technology
2. Industry

This would leave us with a set of models/projects that would showcase specific capabilities we have.

On the technology section, we would have complex DMN files, showing advanced features. Complex BPMN processes, integrating with DMN files, which integrate with PMML files. The whole package. I see it being like a "reference" of everything our technology can do.

On the industry section, we would have tailored examples for business people to identify with, examples that appeal to them as something related to their day-to-day. A financial analyst could see a "Loan approval" decision, or even a "Loan" process. Someone from the health administration sector could see a "ICU admission" decision, or even a "Patient discharge" process.

We can showcase this "BAMOE Library" as a standalone project, or even make it part of KIE Sandbox someway, so people can start playing with the examples easily.

I'd love to know what you think and how do you see us reaching this point.

**Comment by LightGuard** [comment]
Wouldn't organization by use case be helpful as well?

**Comment by LightGuard** [comment]
I suppose that's what you have with "industry."

**Comment by tiagobento** [comment]
Yes, exactly... I think use-cases must be related to some broader scope, like an industry... these would be "real world" cases, of course. I think, however, we can have other examples too, that can be more "fun", like a Decision for situation like, idk, "Should the chicken cross the road?"... Sometimes it's important to see a technology being used out of its normal context to realize its full potential...

Anyway... anything goes, I think :)

**Comment by LightGuard** [comment]
The first step in this will be to create a list of our examples, identify any holes, and further categorize them. @inodeman will you take this first task?

**Comment by a-kshesh** [comment]
Directed to add my thoughts here from the Kogito's Zulip conversation. The complete models will be good choice to go as it will represent the whole idea and  also in future I think there is a plan on providing extended services support for BPMN to run on the sandbox and in that case having an example that is a full model gives better picture of kie-sandbox and Kogito as a whole. Also, showcasing some advance model in a different category/sub-category can be doable as well to show the advance capabilities that the kogito is capable.

I am assuming that this feature implementation will provide the ability to configure the category labels as well as its templates so that the Sandbox can be customizable for the use-case as discussed on the [Zulip](https://kie.zulipchat.com/#narrow/stream/232680-tooling/topic/More.20samples.20on.20KIE.20Sandbox).

**Comment by LightGuard** [comment]
@a-kshesh Sounds like a good idea. Do you have an example you would like to put forward? Maybe start a Google Doc with some ideas at least?
